### ISSUE TITLE
Glitch in safari mobile

### ISSUE THREAD

**Issue by mhedengren** [KyleAMathews/react-headroom#185] opened 2020-10-02 16:51 UTC
I saw that this was an issue back in 2018-2019 but the exact same issue is happing for me now (using gatsby).

The issue back then https://github.com/KyleAMathews/react-headroom/issues/154 

Is anyone else experiencing this?

**Comment by rajinwonderland** [comment] 2020-10-09 00:57
Having the same issue

**Comment by olerichter00** [comment] 2020-12-14 17:35
I'm experiencing the same 👍

**Comment by janczizikow** [comment] 2020-12-14 17:52
@olerichter00 would it be possible to share a link to a repo that reproduces this?

**Comment by olerichter00** [comment] 2020-12-14 21:37
@janczizikow sure, you can reproduce it with this repo: https://github.com/olerichter00/h4ckernews

I could reproduce the glitches with Safari on MacOS (iOS, Chrome and Firefox seem to work as expected).

**Comment by olerichter00** [comment] 2020-12-14 22:14
Delaying the state change to `unfixed` with `setTimout()` seems to prevent the glitches (https://github.com/KyleAMathews/react-headroom/pull/194). Although the header still disappears for a few milliseconds when scrolling to the top fastly.

Related Commit, that apparently introduced the Glitch in 2018: https://github.com/KyleAMathews/react-headroom/commit/c56d15fbd0087b211394eca435f7cfaa4c1bfcf2

**Comment by endymion1818** [comment] 2021-04-19 20:06
Hi @olerichter00 please could you confirm if the latest release fixes the issue for you?

**Comment by olerichter00** [comment] 2021-04-20 09:16
> Hi @olerichter00 please could you confirm if the latest release fixes the issue for you?

Yes, the latest release fixed the issue for me!

**Comment by endymion1818** [comment] 2021-04-20 11:18
Cool!

**Comment by endymion1818** [comment] 2022-04-28 09:29
Closing in favor of #195 because sadly the issue is recurring for some users.

**Closed by endymion1818** 2022-04-28 09:29 UTC
