### ISSUE TITLE
Headroom example on github pages seems broken

### ISSUE THREAD

**Issue by amrit92** [KyleAMathews/react-headroom#82] opened 2016-05-27 14:47 UTC
https://kyleamathews.github.io/react-headroom/

Doesn't seem to work on Chrome

**Comment by KyleAMathews** [comment] 2016-05-27 17:05
hrmmm... thanks, looking into this.

**Comment by KyleAMathews** [comment] 2016-05-27 18:59
Ok, should be fixed. Looks like Gatsby 0.11.1 had a regression which affected this site.

**Closed by KyleAMathews** 2016-05-27 18:59 UTC

**Comment by amrit92** [comment] 2016-05-27 19:04
Thanks @KyleAMathews
