### ISSUE TITLE
Didn't run build script.

### ISSUE THREAD

**Issue by MarcusHong** [KyleAMathews/react-headroom#161] opened 2019-02-28 10:27 UTC
v2.2.5
You missed "build" command.
/node_modules/react-headroom/dist is absent.

**Comment by activist** [comment] 2019-02-28 10:33
This seems to be the cause of an error upstream here as well.

**Comment by endymion1818** [comment] 2019-02-28 10:57
Sorry, my fault — should be fixed now. Please let me know if not.

**Closed** 2019-03-01 10:29 UTC
