### ISSUE TITLE
Headroom class not updating when scrolling up and down very fast

### ISSUE THREAD

**Issue by vjanuar** [KyleAMathews/react-headroom#147] opened 2018-08-02 10:28 UTC
We're using the Headroom component with `disableInlineStyles,` and when scrolling up and down very fast, the `headroom--unpinned` class remains on the header even at the very top, resulting in the header not showing up due to the `transform: translateY(-100%)` property we have under the unpinned CSS selector. Any idea why?

**Comment by fzaninotto** [comment] 2018-09-19 15:56
Same here without the `disableInlineStyles` options. Just a simple `<Headroom>{children}</Headroom>`. 

![kapture 2018-09-19 at 17 55 39](https://user-images.githubusercontent.com/99944/45765416-4dd6a000-bc35-11e8-9d33-f5a7b45d39f4.gif)


This happens very often, I think it's a serious bug.

**Comment by fzaninotto** [comment] 2018-09-19 16:00
I think it's a duplicate of #134

**Comment by fzaninotto** [comment] 2018-09-22 09:45
Fixed by #151.

**Comment by janczizikow** [comment] 2020-10-28 09:35
going to close this, feel free to re-open if it's still an issue

**Closed by janczizikow** 2020-10-28 09:35 UTC
